/** Font. */
import { Montserrat } from 'next/font/google';

/** Global styles. */
import './styles/globals.css';
import './styles/vendors/hamburger.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`gotham text-slate-200 p-2 ${montserrat.className}`}>{children}</body>
    </html>
  );
}
